language: go
branches:
  only: master
# https://github.com/golang/dep/issues/1916
# https://github.com/travis-ci/travis-ci/issues/8301
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
script: make test
